#!/usr/bin/env python3

import argparse
import copy
import functools as ft
import json
import select
import socket
from typing import Dict, List

#DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
    routes = None
    updates = None
    relations = None
    sockets = None
    forwarding_table = None

    def __init__(self, asn: str, networks: List[Dict[str, str]]):
        # map from port to list of IP addresses it can reach
        self.routes = {}
        # cached copy of update announcement (whole packets)
        self.updates = []
        # map from ip address to type of relationship
        self.relations = {}
        # map from ip address to connection object
        self.sockets = {}
        # array of map<string, string> from description to IP address
        self.forwarding_table = []
        # this router's Autonomous System Number
        self.asn = asn
        for relationship in networks:
            network, relation = relationship.split("-")
            if DEBUG: 
                print("Starting socket for", network, relation)
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
        return

    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        outroutes = []
        for route in self.forwarding_table:
            anded_address = self.and_addresses(daddr, route[NMSK])
            if anded_address == route[NTWK]:
                outroutes.append(route)
        return outroutes

    def and_addresses(self, daddr: str, other_addr: str) -> str:
        daddr_sept = daddr.split(".")
        other_addr_sept = other_addr.split(".")
        all_anded = []
        for i in range(len(daddr_sept)):
            all_anded.append(str(int(daddr_sept[i]) & int(other_addr_sept[i])))
        return ft.reduce(lambda x, y: x + "." + y, all_anded)


    def get_shortest_as_path(self, routes) -> List[str]:
        """ select the route with the shortest AS Path """
        if len(routes) <= 0:
            return []
        
        shortest_path = [routes[0]]
        min_path = len(routes[0][APTH])
        for route in routes:
            r_len = len(route[APTH])
            if r_len < min_path:
                min_path = r_len
                shortest_path = [route]
            elif r_len == min_path:
                shortest_path.append(route)
     
        return shortest_path
            
    def get_highest_preference(self, routes):
        """ select the route with the highesr localPref """
        if len(routes) <= 0:
            return []
        
        highest_lprf_route = [routes[0]]
        highest_lprf = int(routes[0][LPRF])
        for route in routes:
            r_lprf = int(route[LPRF])
            if r_lprf > highest_lprf:
                highest_lprf = r_lprf
                highest_lprf_route = [route]
            elif r_lprf == highest_lprf:
                highest_lprf_route.append(route)
     
        return highest_lprf_route
         
    def get_self_origin(self, routes):
        """ select self originating routes """
        print(routes)
        outroutes = []

        if len(routes) <= 0:
            return []
        for route in routes:
            if route[SORG]:
                outroutes.append(route)
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: IGP > EGP > UNK """
        outroutes = []
        current_best = "UNK"

        for route in routes:
            if route[ORIG] == current_best:
                outroutes.append(route)
            elif (route[ORIG] == "EGP" and current_best != "IGP") or route[ORIG] == "IGP":
                # if the current best is worse than EGP and the current is EGP,
                # update best and start a new list
                # if the current best is worse than IGP and the current is IGP,
                # update best and start a new list
                current_best = route[ORIG]
                outroutes = [route]

        return outroutes

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        rel = self.relations[srcif]
        for route in routes:
            opp_rel = self.relations[route[PEER]]
            if (rel == CUST or opp_rel == CUST) or (rel == PROV and opp_rel == PROV):
                outroutes.append(route)
        return outroutes
        
    def get_lowest_ip(self, routes):
        """ select route with the lowest ip address """
        outroutes = []
        min_ip = "255.255.255.255"
        for route in routes:
            r_ip = route[PEER]
            if self.compare_ip(min_ip, r_ip) == 1:
                min_ip = r_ip
                outroutes = [route]
            elif self.compare_ip(min_ip, r_ip) == 0:
                outroutes.append(route)

        return outroutes

    def compare_ip(self, curr_ip, peer):
        curr_nums = list(map(int, curr_ip.split(".")))
        peer_nums = list(map(int, peer.split(".")))

        for i in range(4):
            if curr_nums[i] > peer_nums[i]:
                return 1
            elif curr_nums[i] < peer_nums[i]:
                return -1
            
        return 0

    def get_route(self, srcif, daddr):
        """	Select the best route for a given address	"""
        # TODO
        routes = self.lookup_routes(daddr)
        # Rules go here
        if routes:
            # 1. Highest Preference
            routes = self.get_highest_preference(routes)
            # 2. Self Origin
            routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            routes = self.get_shortest_as_path(routes)
            # 4. IGP > EGP > UNK
            routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            routes = self.get_lowest_ip(routes)
            # Final check: enforce peering relationships
            routes = self.filter_relationships(srcif, routes)
        return routes[0]

    def forward(self, srcif, packet) -> bool:
        """	Forward a data packet	"""
        chosen_route = self.get_route(srcif, packet[DEST])
        if chosen_route is None:
            self.send_error(srcif, packet)
            return False
        self.sockets[chosen_route[PEER]].sendall(json.dumps(packet).encode())
        return True

    def coalesce(self):
        """	coalesce any routes that are right next to each other	"""
        # TODO (this is the most difficult task, save until last)
        return False

    def update(self, srcif, packet) -> bool:
        """    handle update packets    """
        packet["srcif"] = srcif
        self.updates.append(packet)
        packetMessage = packet[MESG]
        self.forwarding_table.append({
            # NTWK
            NTWK: packetMessage[NTWK],
            # NMSK
            NMSK: packetMessage[NMSK],
            # PEER IP
            PEER: packet[SRCE],
            # Local Pref
            LPRF: packetMessage[LPRF],
            # Self Origin
            SORG: packetMessage[SORG],
            # AS Path
            APTH: packetMessage[APTH],
            # Origin
            ORIG: packetMessage[ORIG]
        })
        source_relationship = self.relations[srcif]
        copy_of_packet = copy.deepcopy(packet)
        copy_of_packet[MESG][APTH].append(int(self.asn))

        if source_relationship == CUST:
            for neighbor in self.sockets.keys():
                if neighbor != srcif:
                    copy_of_packet[SRCE] = ('.').join(neighbor.split('.', 3)[:3]) + '.1'
                    copy_of_packet[DEST] = neighbor
                    sending_msg = json.dumps(copy_of_packet).encode()
                    self.sockets[neighbor].sendall(sending_msg)
        else:
            for neighbor in self.sockets.keys():
                if neighbor != srcif and self.relations[neighbor] not in [PROV,PEER]:
                    copy_of_packet[SRCE] = ('.').join(neighbor.split('.', 3)[:3]) + '.1'
                    copy_of_packet[DEST] = neighbor
                    sending_msg = json.dumps(copy_of_packet).encode()
                    self.sockets[neighbor].sendall(sending_msg)

        return True

    def revoke(self, packet) -> bool:
        """	handle revoke packets	"""
        # TODO
        return True

    def dump(self, packet) -> bool:
        """Handles dump table requests by crafting a table message."""
        copy_of_packet = copy.deepcopy(packet)
        copy_of_packet[SRCE] = packet[DEST]
        copy_of_packet[DEST] = packet[SRCE]
        copy_of_packet[TYPE] = TABL
        msg_arr = []
        for route in self.forwarding_table:
            msg_arr.append({NTWK: route[NTWK], NMSK: route[NMSK], PEER: route[PEER]})
        copy_of_packet[MESG] = msg_arr
        sending_msg = json.dumps(copy_of_packet).encode()
        # send table response to original source (who requested the dump data)
        self.sockets[copy_of_packet[DEST]].sendall(sending_msg)
        return True

    def handle_packet(self, srcif, packet) -> bool:
        """	dispatches a packet """
        typeOfPacket = packet["type"]
        if typeOfPacket == DATA:
            return self.forward(srcif, packet)
        elif typeOfPacket == DUMP:
            return self.dump(packet)
        elif typeOfPacket == UPDT:
            return self.update(srcif, packet)
        elif typeOfPacket == RVKE:
            return self.revoke(packet)
        else:
            return False

    def send_error(self, conn, msg):
        """ Send a no_route error message """
        message = {}
        message[SRCE] = conn
        message[DEST] = msg[SRCE]
        message[TYPE] = NRTE
        message[MESG] = {}
        sending_msg = json.dumps(message).encode()
        self.sockets[conn].sendall(sending_msg)
        return True 

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return

if __name__ == "__main__":
    router = Router(args.asn, args.networks)
    router.run()
